"""Clean up schema duplicates and add UniqueCode to env.py

Revision ID: 2223e61fce0c
Revises: f8220d3ceced
Create Date: 2025-09-03 21:08:41.168135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2223e61fce0c'
down_revision: Union[str, Sequence[str], None] = 'f8220d3ceced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
