"""Adicionar tabelas MaterialType e Discard

Revision ID: 9d8ee4eaa708
Revises: ff6d2530ad61
Create Date: 2025-08-19 23:19:44.828151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8ee4eaa708'
down_revision: Union[str, Sequence[str], None] = 'ff6d2530ad61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('points_per_unit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_types_id'), 'material_types', ['id'], unique=False)
    op.create_index(op.f('ix_material_types_name'), 'material_types', ['name'], unique=True)
    op.create_table('discards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discards_id'), 'discards', ['id'], unique=False)
    op.create_index(op.f('ix_discards_unique_code'), 'discards', ['unique_code'], unique=True)
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_index(op.f('ix_discards_unique_code'), table_name='discards')
    op.drop_index(op.f('ix_discards_id'), table_name='discards')
    op.drop_table('discards')
    op.drop_index(op.f('ix_material_types_name'), table_name='material_types')
    op.drop_index(op.f('ix_material_types_id'), table_name='material_types')
    op.drop_table('material_types')
    # ### end Alembic commands ###
