"""Add UniqueCode model and refine Discard/MaterialType models

Revision ID: cd47f70a2ce2
Revises: 9d8ee4eaa708
Create Date: 2025-08-23 21:10:19.176048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd47f70a2ce2'
down_revision: Union[str, Sequence[str], None] = '9d8ee4eaa708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_unique_codes_id'), 'unique_codes', ['id'], unique=False)
    op.add_column('discards', sa.Column('unique_code_id', sa.Integer(), nullable=False))
    op.alter_column('discards', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('discards', 'points_awarded',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('ix_discards_unique_code'), table_name='discards')
    op.create_unique_constraint(None, 'discards', ['unique_code_id'])
    op.create_foreign_key(None, 'discards', 'unique_codes', ['unique_code_id'], ['id'])
    op.drop_column('discards', 'unique_code')
    op.alter_column('material_types', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('material_types', 'points_per_unit',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_types', 'points_per_unit',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('material_types', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('discards', sa.Column('unique_code', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'discards', type_='foreignkey')
    op.drop_constraint(None, 'discards', type_='unique')
    op.create_index(op.f('ix_discards_unique_code'), 'discards', ['unique_code'], unique=True)
    op.alter_column('discards', 'points_awarded',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('discards', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('discards', 'unique_code_id')
    op.drop_index(op.f('ix_unique_codes_id'), table_name='unique_codes')
    op.drop_table('unique_codes')
    # ### end Alembic commands ###
