"""Add material_type_id to UniqueCode and update code length

Revision ID: f8220d3ceced
Revises: cd47f70a2ce2
Create Date: 2025-09-03 20:11:22.919286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8220d3ceced'
down_revision: Union[str, Sequence[str], None] = 'cd47f70a2ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_codes', sa.Column('material_type_id', sa.Integer(), nullable=False))
    op.alter_column('unique_codes', 'code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'unique_codes', 'material_types', ['material_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unique_codes', type_='foreignkey')
    op.alter_column('unique_codes', 'code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('unique_codes', 'material_type_id')
    # ### end Alembic commands ###
