"""Add name, cpf, phone_number to User model

Revision ID: ff6d2530ad61
Revises: 
Create Date: 2025-08-16 22:10:13.461439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff6d2530ad61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('cpf', sa.String(length=11), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
